# StarBreaker CI/CD Pipeline
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Quick checks that run fast
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}--cargo-check-${{ hashFiles('**/Cargo.lock') }}
          retore-keys: |
            ${{ runner.os }}--cargo-check-
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy lints
        run: cargo clippy --workspace --all-targets -- -D warnings

  # Build and test on multiple platforms
  test:
    name: Test (${{ matrix.os }})
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matix.target }}
      
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}--cargo-test-${{ hashFiles('**/Cargo.lock') }}
          retore-keys: |
            ${{ runner.os }}--cargo-test-
      
      - name: Build
        run: cargo build --workspace --all-targets

      - name: Run tests
        run: cargo test --workspace --all-targets

      - name: Run doc tests
        run: cargo test --workspace --doc

  # Build release binaries
  build-release:
    name: Build Release (${{ matrix.os }})
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: starbreaker-linux-x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: starbreaker-windows-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: starbreaker-macos-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: starbreaker-macos-arm64
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.target }}
        
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build release binary
        run: cargo build --release --target ${{ matrix target }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            target/${{ matrix.target }}/release/starbreaker*
            !target/${{ matrix.target }}/release/*.d
  
  # Generate documentation
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable

      - name: Build documentation
        run: cargo doc --workspace --no-deps --all-features

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: target/doc
  
  # Run benchmars (only on main)
  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@4

      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable

      - name: Run benchmars
        run: cargo bench --workspace -- --noplot